- name: Setup Laptop Environment
  hosts: localhost
  become: yes
  vars:
    dotfiles_repo: "https://github.com/Privlak/dotfiles.git"
    dotfiles_dir: "~/dotfiles"
    oh_my_posh_theme_url: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/atomic.omp.json"
    log_file: "~/setup_errors.log"

  tasks:
    - name: Install Essential Packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - neofetch
        - htop
        - bash
        - git
        - python3
        - libreoffice
        - virtualbox
        - vlc
        - google-chrome-stable

    - name: Add Google Chrome repository key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome APT repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present   

    - name: Install VSCode
      snap:
        name: code
        classic: yes
        state: present
      register: vscode_install

    - name: Install Obsidian via Snap
      community.general.snap:
        name: obsidian
        classic: yes
      when: ansible_distribution == "Ubuntu"
      register: obsidian_install
